SELECT * FROM BOARD;


INSERT INTO BOARD (TITLE, CONTENT, WRITER)
VALUES('안녕1','하이1','헬로1');
INSERT INTO BOARD (TITLE, CONTENT, WRITER)
VALUES('안녕2','하이2','헬로2');
INSERT INTO BOARD (TITLE, CONTENT, WRITER)
VALUES('안녕3','하이3','헬로3');
INSERT INTO BOARD (TITLE, CONTENT, WRITER)
VALUES('안녕4','하이4','헬로4');
INSERT INTO BOARD (TITLE, CONTENT, WRITER)
VALUES('안녕5','하이5','헬로5');
INSERT INTO BOARD (TITLE, CONTENT, WRITER)
VALUES('안녕6','하이6','헬로6');
INSERT INTO BOARD (TITLE, CONTENT, WRITER)
VALUES('안녕7','하이7','헬로7');